name: FactionsWealth
version: 1.2.0
main: net.kyuzi.factionswealth.FactionsWealth
author: Nathan
softdepend: [Factions, PlaceholderAPI, SilkSpawners]
commands:
  fwealthreload:
    description: Reload all configuration values.